#!/bin/bash

low_rpm=1500       #Variable for Low RPM Exhaust Fan
high_rpm=5500	   #Variable for High RPM Exhaust Fan

config_file=/etc/macfanctl.conf			#Variable for the Config-File

old_rpm=$(cat $config_file | egrep ^fan_min | cut -d" " -f 2) #Variable for "old" RPM
old_rpm2=$old_rpm					      #Workaround for "old" RPM Variable

	current_rpm=$(cat $config_file | egrep ^fan_min | cut -d" " -f 2);	#Display current RPM
	current_rpm2=$current_rpm
	echo  "Current Exhaustfan RPM $current_rpm";

case $1 in
	low)
	current_rpm=$(cat $config_file | egrep ^fan_min | cut -d" " -f 2);
	current_rpm2=$current_rpm							
	sed -i "s@$current_rpm2@$low_rpm@" $config_file  #"s@$VARIABLE@$Variable@" file
	echo "Setting Exhaustfan RPM to $low_rpm";

	current_rpm=$(cat $config_file | egrep ^fan_min | cut -d" " -f 2);
	current_rpm2=$current_rpm
	echo "New Exhaustfan RPM is $current_rpm";
	fan_pid=$(ps ax | grep macfanctld | cut -d"?" -f 1 | head -1);
	sudo kill -SIGHUP $fan_pid;
 	;;
	
	high)
	current_rpm=$(cat $config_file | egrep ^fan_min | cut -d" " -f 2);
	current_rpm2=$current_rpm
	sed -i "s@$current_rpm2@$high_rpm@" $config_file  #"s@$VARIABLE@$Variable@" file

	echo "Setting Exhaustfan RPM to $high_rpm";
	
	current_rpm=$(cat $config_file | egrep ^fan_min | cut -d" " -f 2);
	current_rpm2=$current_rpm
	echo "New Exhaustfan RPM is $current_rpm";
	
	fan_pid=$(ps ax | grep macfanctld | cut -d"?" -f 1 | head -1);
	sudo kill -SIGHUP $fan_pid;
	;;
	
esac
